### ISSUE TITLE
How to install this??????????????????????????????????????????????????????

### ISSUE THREAD

**Issue by DO1YOUR1BALLS1HANG1LOW** [Tommsy64/SmartMovingReloaded#11]
PLEASE PLEASE PLEASE PLEASE ANSWER THIS QUESTION!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (or ur balls will hang very low)
**### _How to install this mod?_**

**Comment by beanaboston** [comment]
What the heck even is this??

**Comment by XvBUSHvX** [comment]
I am not affiliated with the development of this mod. However because both of these questions are easily answerable I'll field for the developers.

Installation: With the existence of this question I feel it would be safe to say you're not familiar with compiling from source. This isn't currently at a stable version so compiling it is a requirement and should only be done for testing. Which is outside the scope of my knowledge, I'm simply waiting for the release version.

What is this? This is a project to update the mod "Smart Moving", currently available on MC version 1.7 and 1.8. This originally provided an expanded movement set including crawling in to single block spaces, smoother flight, climbing and more. 

The original mod can be downloaded at curseforge and installed according to the standard method of installing forge compatible mods for the appropriate minecraft versions.

**Comment by beanaboston** [comment]
Actually there are some "releases" you can download and use on this GitHub page.

**Comment by XvBUSHvX** [comment]
So there is, I sadly missed. 

In that case it would require a Minecraft client and forge to be installed.

**Comment by ScienceDrummer** [comment]
So can we close this issue or?
